### ISSUE TITLE
glslangValidator crashes when generating debug information

### ISSUE THREAD

**Issue by renatahodovan** [KhronosGroup/glslang#1333]
**Checked versions:**
* local release build, GIT hash #95b1334a
* master-tot linux prebuilt binary (release / debug)

**OS:**
* Ubuntu 17.10, x86_64

**Reproduction:**
Run `glslangValidator` with (probably) arbitrary shader code and the `-g` cli option. It works with even an empty file.

**Backtrace:** (from the prebuilt linux debug binary)
```
Program received signal SIGSEGV, Segmentation fault.
__strlen_avx2 () at ../sysdeps/x86_64/multiarch/strlen-avx2.S:62
62	../sysdeps/x86_64/multiarch/strlen-avx2.S: No such file or directory.
(gdb) bt
#0  __strlen_avx2 () at ../sysdeps/x86_64/multiarch/strlen-avx2.S:62
#1  0x00007ffff7904164 in std::string::operator=(char const*) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#2  0x00000000007f738f in glslang::TIntermediate::setSourceFile (this=0x7fffffffd1e0, file=0x0)
    at /home/travis/build/KhronosGroup/glslang/glslang/MachineIndependent/localintermediate.h:622
#3  0x00000000007f2199 in (anonymous namespace)::ProcessDeferred<(anonymous namespace)::DoFullParse> (compiler=0x17482b0, 
    shaderStrings=0x7fffffffd808, numStrings=1, inputLengths=0x0, stringNames=0x0, customPreamble=0xc5e6ec "", optLevel=EShOptNone, 
    resources=0x1021d80 <Resources>, defaultVersion=100, defaultProfile=ENoProfile, forceDefaultVersionAndProfile=false, 
    forwardCompatible=false, messages=EShMsgDebugInfo, intermediate=..., processingContext=..., requireNonempty=true, includer=..., 
    sourceEntryPointName=<incomplete type>, environment=0x0)
    at /home/travis/build/KhronosGroup/glslang/glslang/MachineIndependent/ShaderLang.cpp:824
#4  0x00000000007e890d in (anonymous namespace)::CompileDeferred (compiler=0x17482b0, shaderStrings=0x7fffffffd808, numStrings=1, 
    inputLengths=0x0, stringNames=0x0, preamble=0xc5e6ec "", optLevel=EShOptNone, resources=0x1021d80 <Resources>, defaultVersion=100, 
    defaultProfile=ENoProfile, forceDefaultVersionAndProfile=false, forwardCompatible=false, messages=EShMsgDebugInfo, intermediate=..., 
    includer=..., sourceEntryPointName=<incomplete type>, environment=0x0)
    at /home/travis/build/KhronosGroup/glslang/glslang/MachineIndependent/ShaderLang.cpp:1197
#5  0x00000000007e84c1 in ShCompile (handle=0x17482b0, shaderStrings=0x7fffffffd808, numStrings=1, inputLengths=0x0, optLevel=EShOptNone, 
    resources=0x1021d80 <Resources>, defaultVersion=100, forwardCompatible=false, messages=EShMsgDebugInfo)
    at /home/travis/build/KhronosGroup/glslang/glslang/MachineIndependent/ShaderLang.cpp:1370
#6  0x00000000007d8f5a in CompileFile (fileName=0x173e6e8 "../../glslang/crash.frag", compiler=0x17482b0)
    at /home/travis/build/KhronosGroup/glslang/StandAlone/StandAlone.cpp:1263
#7  0x00000000007d8c8d in CompileShaders (worklist=...) at /home/travis/build/KhronosGroup/glslang/StandAlone/StandAlone.cpp:751
#8  0x00000000007daf6c in singleMain () at /home/travis/build/KhronosGroup/glslang/StandAlone/StandAlone.cpp:1144
#9  0x00000000007db2a6 in main (argc=3, argv=0x7fffffffdc98) at /home/travis/build/KhronosGroup/glslang/StandAlone/StandAlone.cpp:1177
```

**Comment by johnkslang** [comment]
I added protection for the crash, but it is a mode of use that does not make sense: asking for debug information without asking to generate any code. There is no place for the debug information to go.
