### ISSUE TITLE
Reproducible crash when trying to output nonSemantic debug information

### ISSUE THREAD

**Issue by mbechard** [KhronosGroup/glslang#3167]
If you compile the attached shader (Suffix renamed)
`glslangValidator -gVS -V -R --amb --aml crash2.frag -o s.spv`

It will crash in `Builder::addDebugScopeAndLine()` due to `currentDebugScopeId` being empty.

[crash2.frag.txt](https://github.com/KhronosGroup/glslang/files/11006207/crash2.frag.txt)

**Comment by arcady-lunarg** [comment]
The crash appears to be happening when processing a global initializer. Here is the backtrace: 
```
#0  0x000055555560f050 in spv::Builder::addDebugScopeAndLine (this=0x7fffffffca28, fileName=619, lineNum=454, column=0)
    at /home/arcady/glslang/SPIRV/SpvBuilder.cpp:147
#1  0x000055555560f47a in spv::Builder::setLine (this=0x7fffffffca28, lineNum=454, 
    filename=0x555557ba7e88 "/project1/raymarchRender3D/shaderLibraries/raytkCore") at /home/arcady/glslang/SPIRV/SpvBuilder.cpp:129
#2  0x00005555555b8944 in (anonymous namespace)::TGlslangToSpvTraverser::visitBinary (this=0x7fffffffc9c0, node=0x555557c23ae8)
    at /home/arcady/glslang/SPIRV/GlslangToSpv.cpp:2114
#3  0x0000555555768dba in glslang::TIntermBinary::traverse (this=0x555557c23ae8, it=0x7fffffffc9c0)
    at /home/arcady/glslang/glslang/MachineIndependent/IntermTraverse.cpp:92
#4  0x0000555555769177 in glslang::TIntermAggregate::traverse (this=0x555557c23c48, it=0x7fffffffc9c0)
    at /home/arcady/glslang/glslang/MachineIndependent/IntermTraverse.cpp:175
#5  0x00005555555d2023 in (anonymous namespace)::TGlslangToSpvTraverser::makeGlobalInitializers (this=0x7fffffffc9c0, initializers=...)
    at /home/arcady/glslang/SPIRV/GlslangToSpv.cpp:5353
#6  0x00005555555bb44f in (anonymous namespace)::TGlslangToSpvTraverser::visitAggregate (this=0x7fffffffc9c0, visit=glslang::EvPreVisit, 
    node=0x5555566bfe88) at /home/arcady/glslang/SPIRV/GlslangToSpv.cpp:2870
#7  0x000055555576901a in glslang::TIntermAggregate::traverse (this=0x5555566bfe88, it=0x7fffffffc9c0)
    at /home/arcady/glslang/glslang/MachineIndependent/IntermTraverse.cpp:159
#8  0x00005555555b39b5 in glslang::GlslangToSpv (intermediate=..., spirv=std::vector of length 0, capacity 0, logger=0x7fffffffd918, 
    options=0x7fffffffd910) at /home/arcady/glslang/SPIRV/GlslangToSpv.cpp:9977
#9  0x00005555555a4c74 in CompileAndLinkShaderUnits (compUnits=std::vector of length 1, capacity 1 = {...})
    at /home/arcady/glslang/StandAlone/StandAlone.cpp:1522
#10 0x00005555555a5305 in CompileAndLinkShaderFiles (Worklist=...) at /home/arcady/glslang/StandAlone/StandAlone.cpp:1613
#11 0x00005555555a57e8 in singleMain () at /home/arcady/glslang/StandAlone/StandAlone.cpp:1688
#12 0x00005555555a5c5d in main (argc=9, argv=0x7fffffffe028) at /home/arcady/glslang/StandAlone/StandAlone.cpp:1742
```

After looking through the shader source, I believe the location in question corresponds to line 1852 in the given file, which would make the problematic code fragment the following:
```glsl
const int RAYTK_STAGE_PRIMARY = 0;
...
int _raytkStage = RAYTK_STAGE_PRIMARY;
```

**Comment by jeremy-lunarg** [comment]
@mbechard Working on this now. Thanks for the shader. I can reproduce the crash.

**Comment by jeremy-lunarg** [comment]
Fixed via https://github.com/KhronosGroup/glslang/pull/3179
